spring:
  application:
    name: promo_it
    debug: true
  datasource:
    url: jdbc:postgresql://localhost:5432/promo_it
    username: promo_it
    password: awerdWdgy!24
    driver-class-name: org.postgresql.Driver
  jdbc:
    template:
      query-timeout: 30
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-durations-as-timestamps: false

logging:
  level:
    org.springframework.jdbc: INFO
    gift.academic: INFO

  file:
    name: /home/michael/Documents/promo_it/src/main/java/gift/academic/promo_it/logs/promo_it.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

jwt:
  secret: "z6V6yB8pL2mR4xT9qW1vN5cN8zQ0xY3hA7bV4mK1pL9sR2tW"


telegram:
  botUsername: MegaVerificationBot
  token: 8315203518:AAGWd2ZZ-PNdjC8q0KsG35ajjMgNHZd8C5g
